version: '3.6'

services:
  monolith:
    build: .
    entrypoint:  []
    ports:
      - "8071:8080"
    environment:
      - SHOP_MONOLITH_BIND_ADDR=:8080
    volumes:
      - ./cmd/:$GO_PROJECT_DIR/cmd/
      - ./pkg/:$GO_PROJECT_DIR/pkg/

  orders:
    build: .
    entrypoint:  []
    ports:
      - "8072:8080"
    environment:
      - SHOP_ORDERS_SERVICE_BIND_ADDR=:8080
      - SHOP_RABBITMQ_ADDR=rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE=orders-to-pay
      - SHOP_SERVICE_ADDR=http://shop:8080
    volumes:
    depends_on:
      - rabbitmq  
  
  payments:
    build: .
    entrypoint:  []
    environment:
      - SHOP_RABBITMQ_ADDR=rabbitmq:5672
      - SHOP_RABBITMQ_ORDERS_TO_PAY_QUEUE=orders-to-pay
      - SHOP_ORDERS_SERVICE_ADDR=http://orders:8080
    volumes:
    depends_on:
      - rabbitmq  
  
  shops:
    build: .
    entrypoint:  []
    ports:
      - "8073:8080"
    environment:
      - SHOP_SERVICE_BIND_ADDR=:8080
    volumes:
    depends_on:
      - rabbitmq